name: Hello world workflow

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:
  
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: hello world
      run: echo "Hello world"
      shell: bash
 
  goodbye:
    runs-on: ubuntu-latest
    steps:
    - name: goodbye world
      run: echo "Goodbye world"
      shell: bash

  linter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Super-linter
      uses: super-linter/Super-linter@v5.7.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
